
server:
  ip: localhost
  port: 9000

#Spring????
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/sims?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root



#mybatis ??
mybatis:
  mapper-locations: classpath:mapper/*.xml #????mybatis??
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



files:
  upload:
    path: /Users/hope4cc/Documents/EasyExcelDemo/files/
    #    path: /home/springboot/files/